// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoIvNc9tAu-bTE6hwb1HYxZ1PalnDGCz4',
    appId: '1:997479363647:web:04c1e26a23e2b6253ef48a',
    messagingSenderId: '997479363647',
    projectId: 'flutter-crypto-project',
    authDomain: 'flutter-crypto-project.firebaseapp.com',
    storageBucket: 'flutter-crypto-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwquWQJrmbfHyKnMMJ42AYCmhJJJKoOww',
    appId: '1:997479363647:android:d679f28429a8cb583ef48a',
    messagingSenderId: '997479363647',
    projectId: 'flutter-crypto-project',
    storageBucket: 'flutter-crypto-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQHvF2howkZYeqipCwQrHpENWtCrb7stI',
    appId: '1:997479363647:ios:596dcae7e1877bea3ef48a',
    messagingSenderId: '997479363647',
    projectId: 'flutter-crypto-project',
    storageBucket: 'flutter-crypto-project.appspot.com',
    iosBundleId: 'ryan.shelldon.flutterCriptoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoIvNc9tAu-bTE6hwb1HYxZ1PalnDGCz4',
    appId: '1:997479363647:web:bf17c63d857cb9953ef48a',
    messagingSenderId: '997479363647',
    projectId: 'flutter-crypto-project',
    authDomain: 'flutter-crypto-project.firebaseapp.com',
    storageBucket: 'flutter-crypto-project.appspot.com',
  );
}
